package be.khleuven.arnautsmichael.chip8;

/**
 *
 * @author  Michaël Arnauts
 */
public class Debug extends javax.swing.JFrame {
    
    private Cpu cpu;
    private Memory memory;
    private CpuDebug cpuDebug;
    
    /** Creates new form Debug */
    public Debug(Cpu cpu, Memory memory) {
        initComponents();
        this.cpu = cpu;
        this.memory = memory;
        cpuDebug = new CpuDebug();
        updateDebug();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelDebug = new javax.swing.JPanel();
        lblV2 = new javax.swing.JLabel();
        lblV2Data = new javax.swing.JLabel();
        lblV0 = new javax.swing.JLabel();
        lblV0Data = new javax.swing.JLabel();
        lblV1 = new javax.swing.JLabel();
        lblV1Data = new javax.swing.JLabel();
        lblV3 = new javax.swing.JLabel();
        lblV3Data = new javax.swing.JLabel();
        lblV4 = new javax.swing.JLabel();
        lblV4Data = new javax.swing.JLabel();
        lblV5 = new javax.swing.JLabel();
        lblV5Data = new javax.swing.JLabel();
        lblV6 = new javax.swing.JLabel();
        lblV6Data = new javax.swing.JLabel();
        lblV7 = new javax.swing.JLabel();
        lblV7Data = new javax.swing.JLabel();
        lblV14 = new javax.swing.JLabel();
        lblV8Data = new javax.swing.JLabel();
        lblV8 = new javax.swing.JLabel();
        lblV9Data = new javax.swing.JLabel();
        lblV9 = new javax.swing.JLabel();
        lblVAData = new javax.swing.JLabel();
        lblVA = new javax.swing.JLabel();
        lblVEData = new javax.swing.JLabel();
        lblVF = new javax.swing.JLabel();
        lblVFData = new javax.swing.JLabel();
        lblVB = new javax.swing.JLabel();
        lblVBData = new javax.swing.JLabel();
        lblVC = new javax.swing.JLabel();
        lblVCData = new javax.swing.JLabel();
        lblVD = new javax.swing.JLabel();
        lblVDData = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        lblSoundData = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        lblDelayData = new javax.swing.JLabel();
        lblIData = new javax.swing.JLabel();
        lblOpcode = new javax.swing.JLabel();
        lblDelay = new javax.swing.JLabel();
        lblSound = new javax.swing.JLabel();
        lblPCData = new javax.swing.JLabel();
        lblOpcodeData = new javax.swing.JLabel();
        lblPOpcode = new javax.swing.JLabel();
        lblPOpcodeData = new javax.swing.JLabel();
        lblOpcodeDesc = new javax.swing.JLabel();
        lblPOpcodeDesc = new javax.swing.JLabel();
        btnStep = new javax.swing.JButton();

        setTitle("Debug");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelDebug.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblV2.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV2.setText("V2");
        jPanelDebug.add(lblV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        lblV2Data.setText("ff");
        jPanelDebug.add(lblV2Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblV0.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV0.setText("V0");
        jPanelDebug.add(lblV0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblV0Data.setText("ff");
        jPanelDebug.add(lblV0Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        lblV1.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV1.setText("V1");
        jPanelDebug.add(lblV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        lblV1Data.setText("ff");
        jPanelDebug.add(lblV1Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblV3.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV3.setText("V3");
        jPanelDebug.add(lblV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        lblV3Data.setText("ff");
        jPanelDebug.add(lblV3Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblV4.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV4.setText("V4");
        jPanelDebug.add(lblV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        lblV4Data.setText("ff");
        jPanelDebug.add(lblV4Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblV5.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV5.setText("V5");
        jPanelDebug.add(lblV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        lblV5Data.setText("ff");
        jPanelDebug.add(lblV5Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblV6.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV6.setText("V6");
        jPanelDebug.add(lblV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        lblV6Data.setText("ff");
        jPanelDebug.add(lblV6Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblV7.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV7.setText("V7");
        jPanelDebug.add(lblV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        lblV7Data.setText("ff");
        jPanelDebug.add(lblV7Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lblV14.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV14.setText("VE");
        jPanelDebug.add(lblV14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lblV8Data.setText("ff");
        jPanelDebug.add(lblV8Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        lblV8.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV8.setText("V8");
        jPanelDebug.add(lblV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        lblV9Data.setText("ff");
        jPanelDebug.add(lblV9Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblV9.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblV9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblV9.setText("V9");
        jPanelDebug.add(lblV9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblVAData.setText("ff");
        jPanelDebug.add(lblVAData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        lblVA.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblVA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVA.setText("VA");
        jPanelDebug.add(lblVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        lblVEData.setText("ff");
        jPanelDebug.add(lblVEData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        lblVF.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblVF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVF.setText("VF");
        jPanelDebug.add(lblVF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lblVFData.setText("ff");
        jPanelDebug.add(lblVFData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        lblVB.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblVB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVB.setText("VB");
        jPanelDebug.add(lblVB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblVBData.setText("ff");
        jPanelDebug.add(lblVBData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        lblVC.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblVC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVC.setText("VC");
        jPanelDebug.add(lblVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lblVCData.setText("ff");
        jPanelDebug.add(lblVCData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        lblVD.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblVD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVD.setText("VD");
        jPanelDebug.add(lblVD, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        lblVDData.setText("ff");
        jPanelDebug.add(lblVDData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        lblPC.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblPC.setText("PC");
        jPanelDebug.add(lblPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        lblSoundData.setText("255");
        jPanelDebug.add(lblSoundData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        lblI.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblI.setText("I");
        jPanelDebug.add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        lblDelayData.setText("255");
        jPanelDebug.add(lblDelayData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        lblIData.setText("ffff");
        jPanelDebug.add(lblIData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        lblOpcode.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblOpcode.setText("N Opcode");
        jPanelDebug.add(lblOpcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        lblDelay.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblDelay.setText("Delay");
        jPanelDebug.add(lblDelay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        lblSound.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblSound.setText("Sound");
        jPanelDebug.add(lblSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        lblPCData.setText("ffff");
        jPanelDebug.add(lblPCData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        lblOpcodeData.setText("6090");
        jPanelDebug.add(lblOpcodeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        lblPOpcode.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblPOpcode.setText("P Opcode");
        lblPOpcode.setEnabled(false);
        jPanelDebug.add(lblPOpcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        lblPOpcodeData.setText("6090");
        lblPOpcodeData.setEnabled(false);
        jPanelDebug.add(lblPOpcodeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        lblOpcodeDesc.setText("add v0, 9");
        jPanelDebug.add(lblOpcodeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, -1));

        lblPOpcodeDesc.setText("add v0, 6");
        lblPOpcodeDesc.setEnabled(false);
        jPanelDebug.add(lblPOpcodeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, -1));

        btnStep.setText("Step");
        btnStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDebug, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDebug, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStep)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        updateDebug();
    }//GEN-LAST:event_formWindowActivated

    private void btnStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStepActionPerformed
        cpu.traceCPU(true);
        updateDebug();
    }//GEN-LAST:event_btnStepActionPerformed
    
    private void updateDebug() {
        lblV0Data.setText(Integer.toHexString(cpu.getReg(0)));// & 0xFF));
        lblV1Data.setText(Integer.toHexString(cpu.getReg(1)));// & 0xFF));
        lblV2Data.setText(Integer.toHexString(cpu.getReg(2)));// & 0xFF));
        lblV3Data.setText(Integer.toHexString(cpu.getReg(3)));// & 0xFF));
        lblV4Data.setText(Integer.toHexString(cpu.getReg(4)));// & 0xFF));
        lblV5Data.setText(Integer.toHexString(cpu.getReg(5)));// & 0xFF));
        lblV6Data.setText(Integer.toHexString(cpu.getReg(6)));// & 0xFF));
        lblV7Data.setText(Integer.toHexString(cpu.getReg(7)));// & 0xFF));
        lblV8Data.setText(Integer.toHexString(cpu.getReg(8)));// & 0xFF));
        lblV9Data.setText(Integer.toHexString(cpu.getReg(9)));// & 0xFF));
        lblVAData.setText(Integer.toHexString(cpu.getReg(10)));// & 0xFF));
        lblVBData.setText(Integer.toHexString(cpu.getReg(11)));// & 0xFF));
        lblVCData.setText(Integer.toHexString(cpu.getReg(12)));// & 0xFF));
        lblVDData.setText(Integer.toHexString(cpu.getReg(13)));// & 0xFF));
        lblVEData.setText(Integer.toHexString(cpu.getReg(14)));// & 0xFF));
        lblVFData.setText(Integer.toHexString(cpu.getReg(15)));// & 0xFF));        
        lblIData.setText(Integer.toHexString(cpu.getRegI()));// & 0xFFFF));

        lblOpcodeData.setText(Integer.toHexString(cpu.getOpCode() & 0xFFFF));
        lblPOpcodeData.setText(Integer.toHexString(cpu.getPOpCode() & 0xFFFF));
        
        lblOpcodeDesc.setText(cpuDebug.getOpcodeDescription(cpu.getOpCode()));
        lblPOpcodeDesc.setText(cpuDebug.getOpcodeDescription(cpu.getPOpCode()));
        
        lblPCData.setText(Integer.toHexString(cpu.getPC() & 0xFFFF));
        
        lblSoundData.setText(Integer.toHexString(cpu.getTimerSound() & 0xFF));
        lblDelayData.setText(Integer.toHexString(cpu.getTimerDelay() & 0xFF));
        
        btnStep.setEnabled(memory.isRomLoaded());
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStep;
    private javax.swing.JPanel jPanelDebug;
    private javax.swing.JLabel lblDelay;
    private javax.swing.JLabel lblDelayData;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblIData;
    private javax.swing.JLabel lblOpcode;
    private javax.swing.JLabel lblOpcodeData;
    private javax.swing.JLabel lblOpcodeDesc;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPCData;
    private javax.swing.JLabel lblPOpcode;
    private javax.swing.JLabel lblPOpcodeData;
    private javax.swing.JLabel lblPOpcodeDesc;
    private javax.swing.JLabel lblSound;
    private javax.swing.JLabel lblSoundData;
    private javax.swing.JLabel lblV0;
    private javax.swing.JLabel lblV0Data;
    private javax.swing.JLabel lblV1;
    private javax.swing.JLabel lblV14;
    private javax.swing.JLabel lblV1Data;
    private javax.swing.JLabel lblV2;
    private javax.swing.JLabel lblV2Data;
    private javax.swing.JLabel lblV3;
    private javax.swing.JLabel lblV3Data;
    private javax.swing.JLabel lblV4;
    private javax.swing.JLabel lblV4Data;
    private javax.swing.JLabel lblV5;
    private javax.swing.JLabel lblV5Data;
    private javax.swing.JLabel lblV6;
    private javax.swing.JLabel lblV6Data;
    private javax.swing.JLabel lblV7;
    private javax.swing.JLabel lblV7Data;
    private javax.swing.JLabel lblV8;
    private javax.swing.JLabel lblV8Data;
    private javax.swing.JLabel lblV9;
    private javax.swing.JLabel lblV9Data;
    private javax.swing.JLabel lblVA;
    private javax.swing.JLabel lblVAData;
    private javax.swing.JLabel lblVB;
    private javax.swing.JLabel lblVBData;
    private javax.swing.JLabel lblVC;
    private javax.swing.JLabel lblVCData;
    private javax.swing.JLabel lblVD;
    private javax.swing.JLabel lblVDData;
    private javax.swing.JLabel lblVEData;
    private javax.swing.JLabel lblVF;
    private javax.swing.JLabel lblVFData;
    // End of variables declaration//GEN-END:variables
    
}
